version: "3.9"

networks:
  simulation-net:
    driver: bridge

services:
  victim:
    build: ./victim
    container_name: victim-container
    networks:
      - simulation-net
    ports:
      - "9999:9999"
    stdin_open: true
    tty: true
